export const types = {
    FETCH_DATA_PENDING:'FETCH_DATA_PENDING',
    FETCH_DATA_SUCCESS:'FETCH_DATA_SUCCESS',
    FETCH_DATA_FAILURE:'FETCH_DATA_FAILURE',
    FETCH_USER_PENDING:'FETCH_USER_PENDING',
    FETCH_USER_FAILURE:'FETCH_USER_FAILURE',
    FETCH_USER_SUCCESS:'FETCH_USER_SUCCESS',
}